app.core.biu:
  common:
    press_to_exit: "Press any key to exit..."
    success_to_login: "Login successful"
  config:
    hint_port_is_in_use: "Current port is in use, please modify the 'sys.host' item in config.yml"
    hint_proxy_in_use: "Proxy %s enabled"
    fail_to_load_config: "Failed to load configuration file, program cannot run normally"
  outdated:
    hint_latest: "Latest"
    hint_exist_new: "New version available"
    fail_to_check: "Failed to check for updates"
    fail_to_check_duo_to_network: "Failed to check for updates, target server may be unresponsive for a long time"
    tell_to_download: "Visit https://github.com/txperl/PixivBiu/releases to download"
    press_to_use_old: "Press any key to continue using old version..."
  network:
    hint_in_check: "Checking network status..."
    fail_pixiv_and_use_bypass: "Cannot access Pixiv, enabling bypassSNI route (may not work properly)"
  login:
    hint_token_only: "Due to Pixiv blocking username/password login, only token login is available now"
    hint_before_start: "Network detection will begin shortly, this process can reduce the probability of being unable to use PixivBiu normally due to network issues"
    fail_to_get_token_due_to_network: "Your network cannot properly perform Pixiv token login, please adjust and try again"
    fail_to_get_token_anyway: "Error occurred while getting token, please try again"
    fail_by_cloudflare_captcha: "Encountered Cloudflare protection during login, may be due to network environment issues. You can try to get a new token or wait a moment before logging in again"
    is_need_to_get_token: "Program will guide you to get the token. Continue? (y / n): "
  ready:
    hint_run: "Running:"
    hint_how_to_use: "Open the address in a modern browser"
    hint_version: "Version:"
    hint_function_types: "API Types:"
    hint_image_service: "Image Service:"
    hint_download_path: "Download Path:"
    hint_program_path: "{APP_DIRECTORY}"
    done_init: "Started"
  others:
    hint_in_update_token: "Attempting token update"

app.common.loginHelper:
  network:
    press_need_to_type_proxy: "Please enter proxy address (can be empty): "
    hint_detect_proxy: "Detected proxy address as %s, need to change? (y / n): "
    is_need_to_type_proxy: "No proxy address detected, need to set manually? (y / n): "
  login:
    hint_intro_step_head: "[Login] Please follow these steps:"
    hint_intro_step_1: "1. Visit: %s?%s"
    hint_intro_step_2: "2. Open browser's 'Dev Console', switch to 'Network' tab"
    hint_intro_step_3: "3. Enable 'Preserve log'"
    hint_intro_step_4: "4. Enter 'callback?' in the 'Filter' textbox"
    hint_intro_step_5: "5. Login to your Pixiv account"
    hint_intro_step_6: "6. After successful login, an item like 'https://app-api.pixiv.net/...&code=...' will appear in the list"
    hint_intro_step_7: "7. Enter the parameter after 'code' into this program"
    fail_code_918: "Code error. Note that the Code required each time the program starts is different, cannot reuse previously obtained Codes, and codes do not include quotation marks."
    fail_code_1508: "Code has expired. Please be quicker when obtaining the code."
