app.core.biu:
  common:
    press_to_exit: "按任意鍵退出..."
    success_to_login: "登入成功"
  config:
    hint_port_is_in_use: "當前端口正在使用中，請修改 config.yml 中的 'sys.host' 項"
    hint_proxy_in_use: "已啟用代理 %s"
    fail_to_load_config: "讀取配置文件失敗，程式無法正常運行"
  outdated:
    hint_latest: "最新"
    hint_exist_new: "有可用的新版本"
    fail_to_check: "檢查更新失敗"
    fail_to_check_duo_to_network: "檢查更新失敗，目標伺服器可能長時間未回應"
    tell_to_download: "前往 https://github.com/txperl/PixivBiu/releases 下載"
    press_to_use_old: "按任意鍵繼續使用舊版本..."
  network:
    hint_in_check: "正在檢查網路狀態..."
    fail_pixiv_and_use_bypass: "無法前往 Pixiv，啟用 bypassSNI 線路 (可能無法正常使用)"
  login:
    hint_token_only: "由於 Pixiv 封鎖使用者名稱/密碼登入，目前只能使用token登入"
    hint_before_start: "即將開始進行網路檢測，此過程可以減少因網路問題導致的無法正常使用 PixivBiu 的機率"
    fail_to_get_token_due_to_network: "Your network cannot properly perform Pixiv token login, please adjust and try again"
    fail_to_get_token_anyway: "Error occurred while getting token, please try again"
    fail_by_cloudflare_captcha: "Encountered Cloudflare protection during login, may be due to network environment issues. You can try to get a new token or wait a moment before logging in again"
    is_need_to_get_token: "Program will guide you to get the token. Continue? (y / n): "
  ready:
    hint_run: "運行中："
    hint_how_to_use: "Open the address in a modern browser"
    hint_version: "版本："
    hint_function_types: "API 類型："
    hint_image_service: "怕圖片服務："
    hint_download_path: "下載路徑："
    hint_program_path: "{APP_DIRECTORY}"
    done_init: "Started"
  others:
    hint_in_update_token: "Attempting token update"

app.common.loginHelper:
  network:
    press_need_to_type_proxy: "Please enter proxy address (can be empty): "
    hint_detect_proxy: "Detected proxy address as %s, need to change? (y / n): "
    is_need_to_type_proxy: "No proxy address detected, need to set manually? (y / n): "
  login:
    hint_intro_step_head: "[Login] Please follow these steps:"
    hint_intro_step_1: "1. Visit: %s?%s"
    hint_intro_step_2: "2. Open browser's 'Dev Console', switch to 'Network' tab"
    hint_intro_step_3: "3. Enable 'Preserve log'"
    hint_intro_step_4: "4. Enter 'callback?' in the 'Filter' textbox"
    hint_intro_step_5: "5. Login to your Pixiv account"
    hint_intro_step_6: "6. After successful login, an item like 'https://app-api.pixiv.net/...&code=...' will appear in the list"
    hint_intro_step_7: "7. Enter the parameter after 'code' into this program"
    fail_code_918: "Code error. Note that the Code required each time the program starts is different, cannot reuse previously obtained Codes, and codes do not include quotation marks."
    fail_code_1508: "Code has expired. Please be quicker when obtaining the code."
